Repository CodingTestKiller/Season3, pull requests merged in 2023-10, with the labels that each got.

#42 [김민수] / 디펜스게임, 순위검색, 등산코스정하기
  8주차/등산코스정하기/kmsu44.py
  8주차/디펜스게임/kmsu44.py
  8주차/순위검색/kmsu44.py
Labels: 8주차

#41 [홍성철] / 디펜스게임, 순위검색, 등산코스정하기
  8주차/등산코스정하기/ironAiken2.py
  8주차/디펜스게임/ironAiken2.py
  8주차/순위검색/ironAiken2.py
Labels: 8주차

#40 [김경원] / 디펜스 게임, 순위 검색, 등산코스 정하기
  8주차/등산코스정하기/masonkimseoul.py
  8주차/디펜스게임/masonkimseoul.py
  8주차/순위검색/masonkimseoul.py
Labels: 8주차

#43 [최예린] / 주차 요금 계산, 리코쳇 로봇, 보석 쇼핑
  9주차/리코쳇로봇/RightHennessy.py
  9주차/보석쇼핑/RightHennessy.kt
  9주차/주차요금계산/RightHennessy.py
Labels: 9주차

#47 [정재경] / 주차 요금 계산, 리코쳇 로봇, 보석 쇼핑
  9주차/리코쳇로봇/therealjamesjung.py
  9주차/보석쇼핑/therealjamesjung.py
  9주차/주차요금계산/therealjamesjung.py
Labels: 9주차

#45 [김경원] / 주차 요금 계산, 리코쳇 로봇, 보석 쇼핑
  9주차/리코쳇로봇/masonkimseoul.py
  9주차/보석쇼핑/masonkimseoul.py
  9주차/주차요금계산/masonkimseoul.py
Labels: 9주차

#44 [홍성철] / 주차 요금 계산, 리코쳇 로봇, 보석 쇼핑
  9주차/리코쳇로봇/ironAiken2.py
  9주차/보석쇼핑/ironaiken2.py
  9주차/주차요금계산/ironAiken2.py
Labels: 9주차

#46 [김민수] / 주차 요금 계산, 리코쳇 로봇, 보석 쇼핑
  9주차/리코쳇로봇/kmsu44.py
  9주차/보석쇼핑/kmsu44.py
  9주차/주차요금계산/kmsu44.py
Labels: 9주차

#48 [최예린] / k진수에서 소수 개수 구하기, 혼자서 하는 틱택토, 풍선 터트리기
  10주차/k진수에서소수개수구하기/RightHennessy.kt
  10주차/풍선터트리기/RightHennessy.py
  10주차/혼자서하는틱택토/RightHennessy.py
Labels: 10주차

#49 [정재경] / k진수에서 소수 개수 구하기, 혼자서 하는 틱택토, 풍선 터트리기
  10주차/k진수에서소수개수구하기/therealjamesjung.py
  10주차/풍선터트리기/therealjamesjung.py
  10주차/혼자서하는틱택토/therealjamesjung.py
Labels: 10주차

#52 [김민수] / k진수에서 소수 개수 구하기, 혼자서 하는 틱택토
  10주차/k진수에서소수개수구하기/kmsu44.py
  10주차/혼자서하는틱택토/kmsu44.py
Labels: 10주차

#51 [김경원] / k진수에서 소수 개수 구하기, 혼자서 하는 틱택토, 풍선 터트리기
  10주차/k진수에서소수개수구하기/masonkimseoul.py
  10주차/풍선터트리기/masonkimseoul.py
  10주차/혼자서하는틱택토/masonkimseoul.py
Labels: 10주차
